//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDR_BE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDREntities : DbContext
    {
        public CDREntities()
            : base("name=CDREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CD> CD { get; set; }
        public virtual DbSet<Rental> Rental { get; set; }
        public virtual DbSet<RentalItem> RentalItem { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<CDRentalCountReport> CDRentalCountReport { get; set; }
    }
}
