//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDR_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDRentalCountReport
    {
        public int CDId { get; set; }
        public string CDTitle { get; set; }
        public Nullable<int> RentalCount { get; set; }
    }
}
